Mobile version
luccamicale/firstcapstone.github.io pull request #1
Opened 2022-09-21 14:52 UTC by luccamicale

I created mi first capstone. I complete all the projecy using HTML CSS and javascript

2022-09-22 18:34 UTC, levy002 requested changes
## Hello @luccamicale   , :wave:
### I'm Levy, your PR reviewer

Good job so far :+1: 
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif)

## Status: REQUIRED CHANGES ♻️
_Check the comments under the review._

- [ ] Kindly make sure to remove unnecessary content on your mobile navigation bar in order to meet the provided design. Kindly the same background color as the Behance design.

   - ### Your design
  ![image](https://user-images.githubusercontent.com/87197412/191823369-190ef30a-37b9-41e8-97b5-68aa38637a46.png)

![image](https://user-images.githubusercontent.com/87197412/191823657-69ae6188-6931-42ca-956e-d80f2fc39180.png)



   - ### Behance design
   ![image](https://user-images.githubusercontent.com/87197412/191823120-bb8f5c9a-17eb-4a80-98e6-54bc82a535a4.png)

- [ ] I highly recommend aligning all partners correctly in order to meet the provided design.

   - ### Your design

    ![image](https://user-images.githubusercontent.com/87197412/191824413-28c32acf-059a-4f32-a216-3d57ecf1e2da.png)


  - ### Behance design
    ![image](https://user-images.githubusercontent.com/87197412/191824322-4251ddb6-4c7e-4fc6-b36b-c5d4829b3e9d.png)

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @levy002 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-22 18:34 UTC, levy002 commented on about.html
> +            </ul>
- [ ] Kindly make sure to wrap your top navigation bar into the `header` tag.
- [ ] I highly recommend you wrap the top bar into the `nav` tag.

2022-09-22 18:34 UTC, levy002 commented on about.html
> +                <li id="english"><a class="nav-inside" href="#"></a>English</li>
- [ ] I highly recommend adding the text to the `a` tag instead of the `li` tag. :wink: 
   
     - ### Example
   `<li><a>Login</a><li>`

2022-09-22 18:34 UTC, levy002 commented on index.html
> +            </ul>
- [ ] Kindly make sure to wrap your top navigation bar into the `header` tag.
- [ ] I highly recommend you wrap the top bar into the `nav` tag.

2022-09-22 18:34 UTC, levy002 commented on index.html
> +                <li id="home"><p class="homee">Home Decoration</p></li>
- [ ] I highly recommend adding the text to the `a` tag instead of the `li` tag. :wink: 
   
     - ### Example
   `<li><a>Login</a><li>`

2022-09-22 18:34 UTC, levy002 commented on style.css
> +
- [ ] Kindly make sure to align correctly your cards, I noticed that it is bigger than the actual width of the page on the mobile version.
 
     - ### Your design on mobile version (width: 375px)
   ![image](https://user-images.githubusercontent.com/87197412/191818620-b949e44a-bcdc-42a3-83a9-85df5ec735a3.png)

- [ ] Kindly make sure to add the `JOIN CAMPAIN` button in order to meet the provided design.

  - ### Behance design
![image](https://user-images.githubusercontent.com/87197412/191820344-7ee59fa4-46f1-4232-97c7-7f6dddf29210.png)

2022-09-22 18:34 UTC, levy002 commented on style.css
> +
- [ ] KIndly adjust your margin in order to align the speakers correctly as the provided design.

  - ### Your design
   ![image](https://user-images.githubusercontent.com/87197412/191819730-8d7ab947-c6ab-4ba7-ad21-eec3d5b60dd9.png)


  - ### Provided design
![image](https://user-images.githubusercontent.com/87197412/191819834-8bbb4f66-344f-4d7b-bbcc-4452735bc2d8.png)

2022-09-22 18:34 UTC, levy002 commented on index.html
> +            </div>
- [ ] Kindly make sure to hide the partner's container on home page page of mobile version in order to stick to the provided design.

   - ### Your design
   ![image](https://user-images.githubusercontent.com/87197412/191821467-0f587a98-0f15-4b9f-b73d-6e5dc21076d4.png)


   - ### Behance design
   ![image](https://user-images.githubusercontent.com/87197412/191821407-58c7250e-a4c2-42c8-ad4e-5896fb17a1c4.png)

2022-09-22 18:34 UTC, levy002 commented on about.html
> +            </div>
- [ ] Kindly make sure to adjust the title styling in order to meet the provided design.

   - ### Your design
   ![image](https://user-images.githubusercontent.com/87197412/191822420-4750b6ae-dfad-4167-b3f3-7700c0d7b8a0.png)

  - ### Behance design

   ![image](https://user-images.githubusercontent.com/87197412/191822307-1b99990b-b803-45fc-96d1-3b544bccf434.png)

2022-09-22 23:35 UTC, luccamicale commented
Hi! I changed all things bad in my project. 
![1](https://user-images.githubusercontent.com/107897361/191869033-0532ea4b-cd7b-42b8-a0ef-3d57261eddcd.PNG)
![5](https://user-images.githubusercontent.com/107897361/191869059-f208cfa7-c0d4-4601-bbd6-f3ac91b3c756.PNG)
![4](https://user-images.githubusercontent.com/107897361/191869062-c7f135b7-5731-47db-a64c-551ce7caceb9.PNG)
![3](https://user-images.githubusercontent.com/107897361/191869063-a60658d1-0228-4aef-afaf-81f71d5d3263.PNG)
![2](https://user-images.githubusercontent.com/107897361/191869065-3e28c48f-4733-44b6-8abc-a76a1c9b7d45.PNG)

Please pay a lot atention! I fixed all things

2022-09-23 00:15 UTC, Ugboaja-Uchechi requested changes
Hi @luccamicale, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights

- Linters are passing ✔️ 
- README is descriptive 👍 


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-23 00:15 UTC, Ugboaja-Uchechi commented on style.css
> +}
- [ ] Great job working on the requested changes 👏 . Unfortunately, one was missed. As the previous reviewer mentioned kindly remove the `partner section` in the `mobile version` `home page` 🙏 

![image](https://user-images.githubusercontent.com/74814780/191872123-95432146-ae94-41af-be14-127ad6add1f2.png)

2022-09-23 01:07 UTC, luccamicale commented
I changed the one thing bad in the project. Now all it is good!!!
![6](https://user-images.githubusercontent.com/107897361/191875802-e978d0e3-952b-4f5a-a690-1c0017be6a40.PNG)

2022-09-23 01:33 UTC, franclobo approved these changes
Hi, @luccamicale, 

#STATUS: APPROVED 👏🏽 👏🏽 👏🏽 
In my opinion, your project is ready for the presentation!  There is nothing else to say other than... it's time to merge it :shipit: 


Good luck! 🎉 

**You could consider:**
- [ ] **[OPTIONAL]** To fix the LICENSE link in your README file we could use `[MIT](./MIT.md)` instead of `[MIT](./LICENSE)` it depends of the file's name.

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

2022-09-23 13:15 UTC, merged